services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "4580:80"
    volumes: 
      - ./reverse-proxy:/etc/nginx/conf.d/
      - ./static:/static
    develop:
      watch:
        - action: sync+restart
          path: ./reverse-proxy
          target: /etc/nginx/conf.d/
        - action: sync
          path: ./static
          target: /static
  alpha:
    build: alpha
    ports:
      - 4500:4500
    develop:
      watch:
        - action: rebuild
          path: ./alpha
  beta:
    build: beta
    ports:
      - 4501:4501
    develop:
      watch:
        - action: rebuild
          path: ./beta
