
services:

  alpha:
    build:
      context: .
    image: ${DOCKER_REGISTRY}/${DOCKER_ORG_NAME}/${REPO_NAME}-alpha:${COMMIT_SHORT_SHA}
    container_name: ${ALPHA_CONTAINER_NAME}
    user: ${ALPHA_USER}
    env_file: [ .env ]
    ports: [ "${ALPHA_PORT}:${ALPHA_PORT}" ]
    restart: "no"
    volumes:
      - ./test:/app/test/
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB
    develop:
      watch:
        - action: rebuild
          path: .
