services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "4580:80"
    volumes: 
      - ./reverse-proxy:/etc/nginx/conf.d/
      - ./static:/static
    develop:
      watch:
        - action: sync+restart
          path: ./reverse-proxy
          target: /etc/nginx/conf.d/
        - action: sync
          path: ./static
          target: /static

  alpha:
    container_name: ${ALPHA_CONTAINER_NAME}
    build: alpha
    env_file: [ .env ]
    read_only: true
    restart: "no"
    volumes:
      - ./alpha/test:/alpha/test/:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB
    ports:
      - 4500:4500
    develop:
      watch:
        - action: rebuild
          path: ./alpha

  beta:
    container_name: ${BETA_CONTAINER_NAME}
    build: beta
    ports:
      - 4501:4501
    develop:
      watch:
        - action: rebuild
          path: ./beta
