services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "4580:80"
    volumes: 
      - ./reverse-proxy:/etc/nginx/conf.d/
      - ./static:/static
    develop:
      watch:
        - action: sync+restart
          path: ./reverse-proxy
          target: /etc/nginx/conf.d/
        - action: sync
          path: ./static
          target: /static

  alpha:
    build:
      context: alpha
    image: ${ALPHA_IMAGE}
    container_name: ${ALPHA_CONTAINER_NAME}
    env_file: [ .env ]
    read_only: true
    restart: "no"
    volumes:
      - ./alpha/test:/alpha/test/:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB
    ports:
      - ${ALPHA_PORT}:${ALPHA_PORT}
    develop:
      watch:
        - action: rebuild
          path: ./alpha

  beta:
    build:
      context: beta
    image: ${BETA_IMAGE}
    container_name: ${BETA_CONTAINER_NAME}
    env_file: [ .env ]
    read_only: true
    restart: "no"
    volumes:
      - ./beta/test:/beta/test/:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 01777
          size: 10485760  # 10MB
    ports:
      - ${BETA_PORT}:${BETA_PORT}
    develop:
      watch:
        - action: rebuild
          path: ./beta
  webapp:
    build: webapp
    ports:
      - "4502:4502"
    volumes:
      - ./webapp:/app
