name: Build alpha on main

on:
  push:
    branches:
      - main
    paths:
      - alpha/**

env:
  DOCKER_REGISTRY: ghcr.io
  GITHUB_ORG_NAME: kosli-dev
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  SERVICE_NAME: alpha


jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.variables.outputs.image_tag }}
      image_name: ${{ steps.variables.outputs.image_name }}
    steps:
      - name: Set outputs
        id: variables
        run: |
          IMAGE_TAG=${GITHUB_SHA:0:7}
          echo "image_tag=${IMAGE_TAG}" >> ${GITHUB_OUTPUT}       
          echo "image_name=${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_ORG_NAME }}/playground-alpha:${IMAGE_TAG}" >> ${GITHUB_OUTPUT}          


  build:
    name: Docker Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push Docker image to the GHCR
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: alpha
        push: true
        tags: ${{ needs.setup.outputs.image_name }}

