name: Build beta on main

on:
  push:
    branches:
      - main
    paths:
      - beta/**


jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - name: Say hello
        run: echo "Hello beta"