name: Build and test webapp on main

on:
  push:
    branches:
      - main
    paths:
      - webapp/**
      - .github/workflows/webapp_main.yml


env:
  SERVICE_NAME: webapp


jobs:
  prepare:
    name: Get docker image for builder
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ env.SERVICE_NAME }}

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: build image
        run: docker build . -t playground/webapp

  test:
    name: Run tests and generate coverage
    needs: ["prepare"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ env.SERVICE_NAME }}

    steps:
      - name: run tests
        run: docker run --rm -v $(pwd):/app playground/webapp coverage

  build:
    name: Build docker image and push it to registry
    needs: ["prepare"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ env.SERVICE_NAME }}

    steps:
    - name: build site
      run: docker run --rm -v $(pwd):/app playground/webapp build

